[package]
name = "peginator"
version = "0.1.0"
edition = "2021"

authors = ["Alex Badics <admin@stickman.hu>"]
license = "MIT"

[[bin]]
name = "peginator-compile"

[dependencies]
quote = "1.0"
proc-macro2 = "1.0"
