# Copyright (C) 2022, Alex Badics
# This file is part of peginator
# Licensed under the MIT license. See LICENSE file in the project root for details.

@export
Test = a:RustRawString b:OtherType;

@extern(crate::extern_directive::raw_string_parser)
RustRawString;

@extern(crate::extern_directive::struct_maker -> crate::extern_directive::TheStruct)
OtherType;
