# Copyright (C) 2022, Alex Badics
# This file is part of peginator
# Licensed under the MIT license. See LICENSE file in the project root for details.

@export
@position
Root = "nice" field:Field field2:OverriddenField "rulerino";

@position
Field = "f" ":" s:Ident;

OverriddenField = "f" ":" @:Ident;

@position
@no_skip_ws
Ident = {'a'..'z'}+;
