# Copyright (C) 2022, Alex Badics
# This file is part of peginator
# Licensed under the MIT license. See LICENSE file in the project root for details.

@export 
AnyButB = !'b' c:char;

@export
AnyButASDF = !('a' | 's' | 'd' | 'f') c:char;

@export
@no_skip_ws
SplitLast = { !(',' {!',' char} $) list_rest:char } ',' {list_last:char} $;
