# Copyright (C) 2022, Alex Badics
# This file is part of peginator
# Licensed under the MIT license. See LICENSE file in the project root for details.

@export
EnumTest = 'a' a:Point | 'b' a:NoFieldName;

@export
EnumTestComplex = 'a' a:Point | ('b' a:NoFieldName | 'c' a:OverrideTest);

@export
OverrideTest = s:SimpleOverride e:EnumOverride o:OptionOverride v:VecOverride;

SimpleOverride = @:Point;

EnumOverride = @:Point | @:NoFieldName;

OptionOverride = [@:Point];

VecOverride = {@:Point};

@export
NoFieldName = "dontcare:" Coordinate f:Coordinate;

@export
Point = '(' x:Coordinate ';' y:Coordinate ')';

@string
@no_skip_ws
Coordinate = {'0'..'9'}+;
