# Copyright (C) 2022, Alex Badics
# This file is part of peginator
# Licensed under the MIT license. See LICENSE file in the project root for details.

@export
Root = parsed:Recursive '.' $;

@memoize
Recursive = 'a' inner:*Recursive 'b' | 'a' inner:*Recursive 'c'|;
