# Copyright (C) 2022, Alex Badics
# This file is part of peginator
# Licensed under the MIT license. See LICENSE file in the project root for details.

@export Simple = c:Tag1 | c:Tag2;
Tag1 = '1';
Tag2 = '2';
